apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations: 
    run.googleapis.com/launch-stage: ALPHA
    run.googleapis.com/ingress: internal-and-cloud-load-balancing 
  name: ${SERVICE_NAME}
spec:
  template:
    metadata:      
      name: ${SERVICE_NAME}-${REVISION_TAG} 
      annotations:
        run.googleapis.com/execution-environment: gen1
        autoscaling.knative.dev/minScale: '3'
        autoscaling.knative.dev/maxScale: '100'
      labels: 
        region: us-east4
        app_code: placeholder
        classification: placeholder
        cost_id: placeholder
        department_id: placeholder
        hca_project_id: placeholder
        tco_id: placeholder
        app_environment: placeholder 
    spec:
      containerConcurrency: 80
      serviceAccountName: ${CLOUD_RUN_SA}
      containers:
      - image: ${CONTAINER_IMAGE}
        name: ${SERVICE_NAME}
        ports: 
        - name: http1
          containerPort: 80
        env:
        - name: PROJECT_ID
          value: ${PROJECT_ID}
  traffic: 
  - latestRevision: true
    percent: 100 