apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: 'hello3'
description: 'Deployment pipeline for demo app'
serialPipeline:
  stages:
    - targetId: 'dev'
      profiles: ['dev']
    - targetId: 'prod'
      profiles: ['prod']
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: 'dev'
description: 'dev target'
run:
  location: projects/${PROJECT_ID}/locations/${REGION}
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: 'prod'
description: 'production target'
run:
  location: 'projects/${PROJECT_ID}/locations/${REGION}'