name: Build and Deploy to Cloud Run
on:
  pull_request:
    branches: [develop, main]
  push:
  workflow_dispatch: 
    inputs: 
      environment: 
        type: choice
        required: true
        default: "prod"
        description: GitHub Environment
        options: 
          - prod

jobs: 
  #DEV
  dev:
    # if: github.ref_name != 'main'
    uses: ./.github/workflows/_deployment.yaml
    permissions: 
      id-token: write
      contents: read
      actions: read
      security-events: write
    with: 
      environment: dev
      ref: ${{ github.sha }}
      gcp_project_id: arched-inkwell-368821
      artifact_registry_repo: reference-architectures
      region: us-east4
      service_name: scan-test
      code_directory: ./code/hello-python
      cloud_run_sa: cloud-run-sa
      language: python
    secrets: inherit
  
  #PROD
  prod: 
    if: github.ref_name == 'main'
    uses: ./.github/workflows/_deployment.yaml
    permissions: 
      id-token: write
      contents: read
      actions: read
      security-events: write
    with: 
      environment: ${{ github.event.inputs.environment }}
      ref: ${{ github.sha }}
      gcp_project_id: arched-inkwell-368821
      artifact_registry_repo: reference-architectures
      region: us-east4
      service_name: pods
      code_directory: ./code/Samples.Run.MarkdownPreview.Editor
      language: python
    secrets: inherit