name: Build and Deploy to Cloud Run
on:
  pull_request:
    branches: [develop, main]
  push:
  workflow_dispatch: 
    inputs: 
      environment: 
        type: choice
        required: true
        default: "prod"
        description: GitHub Environment
        options: 
          - prod

jobs: 
  #DEV
  dev:
    if: github.ref_name != 'main'
    uses: ./.github/workflows/_deployment.yaml
    permissions: 
      id-token: write
      contents: read
      actions: read
      security-events: write
    with: 
      artifact_registry_repo: blueprints
      cloud_run_sa: cloud-run-sa
      code_directory: ./code/hello-python
      environment: dev
      gcp_project_id: hca-demo-dev
      language: python
      ref: ${{ github.sha }}
      region: us-east4
      service_name: sample-service
    secrets: inherit
  
  #QA
  qa: 
    if: github.ref_name == 'main' && github.event_name == 'push'
    uses: ./.github/workflows/_deployment.yaml
    permissions: 
      id-token: write
      contents: read
      actions: read
      security-events: write
    with: 
      artifact_registry_repo: blueprints
      cloud_run_sa: cloud-run-sa
      code_directory: ./code/hello-python
      environment: qa
      gcp_project_id: hca-demo-qa
      language: python
      ref: ${{ github.sha }}
      region: us-east4
      service_name: sample-service
    secrets: inherit

  #PROD
  prod: 
    if: inputs.environment == 'prod' && github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/_deployment-prod.yaml
    permissions: 
      id-token: write
      contents: read
      actions: read
      security-events: write
    with: 
      artifact_registry_repo: blueprints
      cloud_run_sa: cloud-run-sa
      code_directory: ./code/hello-python
      environment: prod
      gcp_project_id: hca-demo-prod
      language: python
      ref: ${{ github.sha }}
      region: us-east4
      service_name: sample-service
    secrets: inherit