name: Build and Deploy to Cloud Run
on:
  pull_request:
    branches: [develop, main]
  push:
  workflow_dispatch: 
    inputs: 
      environment: 
        type: choice
        required: true
        default: "prod"
        description: GitHub Environment
        options: 
          - prod
      new_revision_percentage: 
        type: choice
        required: true
        default: '10'
        description: New Cloud Run revision traffic percentage
        options: 
          - "10"
          - "25"
          - "50"
          - "75"
          - "90"
          - "100"
      old_revision_percentage: 
        type: choice
        required: true
        default: '90'
        description: Old Cloud Run revision traffic percentage
        options: 
          - "10"
          - "25"
          - "50"
          - "75"
          - "90"
          - "100"
      old_revision_name:
        type: string
        required: true
        description: Old Cloud Run revision name. 

jobs: 
  #DEV
  dev:
    if: github.ref_name != 'main'
    uses: ./.github/workflows/_deployment.yaml
    permissions: 
      id-token: write
      contents: read
      actions: read
      security-events: write
    with: 
      environment: dev
    secrets: inherit
  
  #QA
  qa: 
    if: github.ref_name == 'main' && github.event_name == 'push'
    uses: ./.github/workflows/_deployment.yaml
    permissions: 
      id-token: write
      contents: read
      actions: read
      security-events: write
    with: 
      environment: qa
    secrets: inherit

  #PROD
  prod: 
    if: inputs.environment == 'prod' && github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/_deployment.yaml
    permissions: 
      id-token: write
      contents: read
      actions: read
      security-events: write
    with: 
      environment: prod
    secrets: inherit