name: Build and Deploy to Cloud Run
on:
  pull_request:
    branches: [develop, main]
  push:
  workflow_dispatch: 
    inputs: 
      environment: 
        type: choice
        required: true
        default: "prod"
        description: GitHub Environment
        options: 
          - prod
      new_revision_percentage: 
        type: choice
        required: true
        default: 10
        description: New Cloud Run revision traffic percentage
        options: 
          - "10"
          - "25"
          - "50"
          - "75"
          - "90"
          - "100"
      old_revision_percentage: 
        type: choice
        required: true
        default: 90
        description: Old Cloud Run revision traffic percentage
        options: 
          - "10"
          - "25"
          - "50"
          - "75"
          - "90"
          - "100"

jobs: 
  #DEV
  dev:
    if: github.ref_name != 'main'
    uses: ./.github/workflows/_deployment.yaml
    permissions: 
      id-token: write
      contents: read
      actions: read
      security-events: write
    with: 
      artifact_registry_repo: blueprints
      cloud_run_sa: cloud-run-sa
      code_directory: ./code/hello-python
      environment: dev
      gcp_project_id: hca-demo-dev
      language: python
      ref: ${{ github.sha }}
      region: us-east4
      service_name: sample-service 
      app_code: sample
      classification: placeholder
      cost_id: placeholder
      department_id: placeholder
      hca_project_id: placeholder
      tco_id: placeholder
    secrets: inherit
  
  #QA
  qa: 
    if: github.ref_name == 'main' && github.event_name == 'push'
    uses: ./.github/workflows/_deployment.yaml
    permissions: 
      id-token: write
      contents: read
      actions: read
      security-events: write
    with: 
      artifact_registry_repo: blueprints
      cloud_run_sa: cloud-run-sa
      code_directory: ./code/hello-python
      environment: qa
      gcp_project_id: hca-demo-qa
      language: python
      ref: ${{ github.sha }}
      region: us-east4
      service_name: sample-service
      app_code: sample
      classification: placeholder
      cost_id: placeholder
      department_id: placeholder
      hca_project_id: placeholder
      tco_id: placeholder
    secrets: inherit

  #PROD
  prod: 
    if: inputs.environment == 'prod' && github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/_deployment-prod.yaml
    permissions: 
      id-token: write
      contents: read
      actions: read
      security-events: write
    with: 
      artifact_registry_repo: blueprints #TODO: add artifact registry project id
      cloud_run_sa: cloud-run-sa
      code_directory: ./code/hello-python
      environment: prod
      gcp_project_id: hca-demo-prod
      language: python
      existing_revision: sample-service-fda0276dea649024885871536ed90f41a05cf42e
      ref: ${{ github.sha }}
      region: us-east4
      service_name: sample-service
      app_code: sample
      classification: placeholder
      cost_id: placeholder
      department_id: placeholder
      hca_project_id: placeholder
      tco_id: placeholder
    secrets: inherit