name: Build and Deploy to Cloud Run
on:
  pull_request:
    branches: [develop, qa, main]
  push:
  workflow_dispatch: 
    inputs: 
      environment: 
        type: choice
        required: true
        default: "prod"
        description: GitHub Environment
        options: 
          - prod

jobs: 
  #DEV
  dev:
    if: github.ref_name != 'main' && ${{ inputs.environment }} != 'prod'
    uses: ./.github/workflows/_deployment.yaml
    permissions: 
      id-token: write
      contents: read
      actions: read
      security-events: write
    with: 
      environment: dev
      ref: ${{ github.sha }}
      gcp_project_id: hca-demo-dev
      artifact_registry_repo: blueprints
      region: us-east4
      service_name: sample-service
      code_directory: ./code/hello-python
      cloud_run_sa: cloud-run-sa
      language: python
    secrets: inherit
  
  #QA
  qa: 
    if: github.ref_name != 'develop' && ${{ inputs.environment }} != 'prod'
    uses: ./.github/workflows/_deployment.yaml
    permissions: 
      id-token: write
      contents: read
      actions: read
      security-events: write
    with: 
      environment: qa
      ref: ${{ github.sha }}
      gcp_project_id: hca-demo-qa
      artifact_registry_repo: blueprints
      region: us-east4
      service_name: sample-service
      code_directory: ./code/hello-python
      language: python
    secrets: inherit

  #PROD
  prod: 
    if: inputs.environment == 'prod' 
    uses: ./.github/workflows/_deployment-prod.yaml
    permissions: 
      id-token: write
      contents: read
      actions: read
      security-events: write
    with: 
      environment: prod
      ref: ${{ github.sha }}
      gcp_project_id: hca-demo-prod
      artifact_registry_repo: blueprints
      region: us-east4
      service_name: sample-service
      code_directory: ./code/hello-python
      language: python
    secrets: inherit