name: Build and Deploy to Cloud Run
on:
  workflow_dispatch:
    inputs:
    environment:
      type: choice
      required: true
      default: "dev"
      description: Deployment Environment
      options:
        - dev
        - qa
        - prod
env: 
  CODE_DIRECTORY: ./code/Samples.Run.MarkdownPreview.Editor

jobs: 
  dev: 
    if: ${{ github.event.inputs.environment == 'dev' }}
    uses: ./.github/workflows/deployment.yaml
    with: 
      environment: ${{ github.event.inputs.environment }}
      ref: ${{ github.ref }}
      gcp_project_id: test
      artifact_registry_repo: reference-architectures
      artifact_registry_location: us-east4
      docker_image_name: pods
      service_name: pods
    secrets: inherit

# env:
#   PROJECT_ID: arched-inkwell-368821                             # TODO: update Google Cloud project id
#   GAR_LOCATION: us-east4                                        # TODO: update Artifact Registry location
#   REPOSITORY: reference-architectures                           # TODO: update Artifact Registry repository name
#   CONTAINER_SERVICE: pods                                       # TODO: update Cloud Run service name
#   REGION: us-east4                                              # TODO: update Cloud Run service region #
#   IMAGE_TAG: latest
#   WORKING_DIRECTORY: ./terraform
#   CLOUD_RUN_SA: cloud-run-sa

